---
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5).to_i %>
:queues:
  - [critical, 6]
  - [default, 3]
  - [low, 2]
  - [very_low, 1]

:scheduler:
  :schedule:
    finish_disbursements_calculation:
      cron: "50 19 * * *" # Everyday 7:50 PM
      class: FinishDisbursementsCalculationJob
